# Generated by Django 3.1.6 on 2021-02-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=1, max_length=25)),
                ('product', models.ManyToManyField(related_name='tags', to='products.Product')),
            ],
        ),
    ]
