# Generated by Django 3.1.6 on 2021-02-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210220_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='tag',
        ),
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='products.Tag'),
        ),
    ]
